name = "dink-url-manager"
main = "src/worker.tsx"
compatibility_date = "2026-05-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_id = "2357bf90-d9b0-4eb4-b1a5-8c1457860579"
migrations_dir = "./migrations"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
